import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderPages from "@/components/header/HeaderPages";
import FooterPages from "@/components/footer/Footer";
import { ShopProvider } from "@/components/store/ShopContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ShopProvider>
          <HeaderPages />
          {children}
          <FooterPages />
        </ShopProvider>
      </body>
    </html>
  );
}
